insert into chirps (id, author, chirp) values (1, 'Tersina Kilminster', 'nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros');
insert into chirps (id, author, chirp) values (2, 'Lindsay Kunz', 'odio elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis');
insert into chirps (id, author, chirp) values (3, 'Allie Fairburne', 'maecenas tristique est et tempus semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum');
insert into chirps (id, author, chirp) values (4, 'Shirleen Maggorini', 'mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum');
insert into chirps (id, author, chirp) values (5, 'Aime Skacel', 'eu nibh quisque id justo sit amet sapien dignissim vestibulum');
insert into chirps (id, author, chirp) values (6, 'Anthia Burberry', 'odio odio elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus');
insert into chirps (id, author, chirp) values (7, 'Emmet Jakubovits', 'at nulla suspendisse potenti cras in purus eu magna vulputate luctus');
insert into chirps (id, author, chirp) values (8, 'Taddeusz Niemetz', 'odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus');
insert into chirps (id, author, chirp) values (9, 'Deeanne Tiley', 'a pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices');
insert into chirps (id, author, chirp) values (10, 'Piggy Kewish', 'odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper');
insert into chirps (id, author, chirp) values (11, 'Daphne Matusovsky', 'turpis enim blandit mi in porttitor pede justo eu massa');
insert into chirps (id, author, chirp) values (12, 'Hansiain Lowton', 'sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque');
insert into chirps (id, author, chirp) values (13, 'Krista Sabate', 'mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum ac lobortis vel dapibus at diam nam tristique');
insert into chirps (id, author, chirp) values (14, 'Alyda Shervil', 'posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus');
insert into chirps (id, author, chirp) values (15, 'Towney Olive', 'amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum');
insert into chirps (id, author, chirp) values (16, 'Caron Mandres', 'risus praesent lectus vestibulum quam sapien varius ut blandit non interdum in ante vestibulum ante ipsum');
insert into chirps (id, author, chirp) values (17, 'Dulcine Hoffman', 'vel est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est');
insert into chirps (id, author, chirp) values (18, 'Jeth Philot', 'odio elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit');
insert into chirps (id, author, chirp) values (19, 'Chicky Verillo', 'eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla');
insert into chirps (id, author, chirp) values (20, 'Dulcine Franek', 'nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet');
insert into chirps (id, author, chirp) values (21, 'Lilla Branca', 'sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra');
insert into chirps (id, author, chirp) values (22, 'Aurelia Grinval', 'at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in');
insert into chirps (id, author, chirp) values (23, 'Matilda Colbeck', 'maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque');
insert into chirps (id, author, chirp) values (24, 'Bailey Ellar', 'nisi eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer');
insert into chirps (id, author, chirp) values (25, 'Dilan Dilgarno', 'dui vel sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis');
insert into chirps (id, author, chirp) values (26, 'Nancie Starbuck', 'curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi');
insert into chirps (id, author, chirp) values (27, 'Chelsy Cone', 'massa volutpat convallis morbi odio odio elementum eu interdum eu tincidunt in leo maecenas');
insert into chirps (id, author, chirp) values (28, 'Jacques Garter', 'ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam');
insert into chirps (id, author, chirp) values (29, 'Renado Milillo', 'leo odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas');
insert into chirps (id, author, chirp) values (30, 'Jameson Ortiger', 'condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse');